apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: capi-clusters
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/RatanVMistry/gitops-capi-argocd-lab.git
        revision: main
        files:
          - path: clusters/*.yaml
          - path: clusters/addons/*.yaml
            exclude: true
  template:
    metadata:
      name: 'capi-{{ trimSuffix ".yaml" .path.filename }}'
      labels:
        app.kubernetes.io/part-of: capi-clusters
    spec:
      project: default
      source:
        repoURL: https://github.com/RatanVMistry/gitops-capi-argocd-lab.git
        targetRevision: main
        path: clusters
        directory:
          recurse: true
          include: '{{ .path.filename }}'
      destination:
        name: kind-mgmt
        namespace: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
